const ic=d=>`<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${d}</svg>`;
const I={cart:ic('<path d="M3 4h2l2.4 11h10.2L20 8H6.2"/><circle cx="9" cy="19" r="1.4"/><circle cx="17" cy="19" r="1.4"/>'),user:ic('<circle cx="12" cy="8" r="4"/><path d="M4 20c1-4 4-6 8-6s7 2 8 6"/>'),userok:ic('<circle cx="12" cy="8" r="4"/><path d="M4 20c1-4 4-6 8-6s7 2 8 6"/><path d="m16 4 2 2 3-3"/>'),
 heart:ic('<path d="M12 20s-7-4.5-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 10c0 5.500-7 10-7 10z"/>'),heartF:ic('<path fill="currentColor" d="M12 20s-7-4.5-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 10c0 5.500-7 10-7 10z"/>'),x:ic('<path d="M6 6l12 12M18 6 6 18"/>'),
 snd:on=>ic('<path d="M4 9v6h4l5 4V5L8 9z"/>'+(on?'<path d="M16 9c1.500 1.500 1.500 4.500 0 6"/>':'<path d="m17 9 4 6m0-6-4 6"/>')),
 sv:[ic('<path d="m12 3 8 4.500v9L12 21l-8-4.500v-9z"/><path d="M12 12v9M4 7.500l8 4.500 8-4.500"/>'),ic('<path d="M4 20l1-5L16 4l4 4L9 19z"/><path d="m14 6 4 4"/>'),ic('<path d="m12 3 9 5-9 5-9-5z"/><path d="m3 13 9 5 9-5"/>'),ic('<path d="M4 5h16v11H9l-5 4z"/>')]};
let AC,mute=localStorage.mute=='1';
function snd(t){if(mute)return;try{AC=AC||new(window.AudioContext||webkitAudioContext)();const n=AC.currentTime,q={click:[[700,.04]],add:[[523,.07],[784,.1]],ok:[[523,.1],[659,.1],[784,.2]],err:[[300,.12],[220,.2]],open:[[440,.05],[587,.07]]}[t]||[];
 q.forEach(([f,d],i)=>{const o=AC.createOscillator(),g=AC.createGain(),s=n+i*.09;o.type=t=='err'?'sawtooth':'sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,s);g.gain.exponentialRampToValueAtTime(.1,s+.01);g.gain.exponentialRampToValueAtTime(.0001,s+d+.05);o.connect(g).connect(AC.destination);o.start(s);o.stop(s+d+.08)})}catch{}}
function confetti(){for(let i=0;i<60;i++){const d=document.createElement('i');d.className='cf';d.style.cssText=`left:${Math.random()*100}vw;background:hsl(${Math.random()*360},80%,65%);animation-delay:${Math.random()*.6}s`;document.body.append(d);setTimeout(()=>d.remove(),3200)}}
document.addEventListener('click',e=>{if(e.target.closest('.btn,.chip,.ib'))snd('click')});
document.addEventListener('mousemove',e=>{const c=e.target.closest('.card,.fr');if(!c)return;const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`perspective(700px) rotateY(${x*9}deg) rotateX(${-y*9}deg) translateY(-4px)`});
document.addEventListener('mouseout',e=>{const c=e.target.closest('.card,.fr');if(c)c.style.transform=''});
const $=(s,r=document)=>r.querySelector(s),C=CONFIG,A=C.api.replace(/\/$/,''),T=n=>(+n).toLocaleString('fa-IR')+' تومان';
const L=(k,d)=>{try{return JSON.parse(localStorage[k])}catch{return d}},S=(k,v)=>localStorage[k]=JSON.stringify(v);
const stl={awaiting_payment:'در انتظار فیش',review:'در حال بررسی',approved:'تأیید شد',rejected:'رد شد'};
async function load(){P=await fetch(A+'/api/products').then(r=>r.json()).catch(()=>[]);if(!P.length&&$('#plist'))$('#plist').innerHTML='<p>اتصال به سرور برقرار نیست. آدرس api را در assets/config.js بررسی کنید.</p>'}
let tok=localStorage.t||'',me=L('u',null),cart=L('cart',[]),wish=L('wish',[]),P=[];
async function api(u,o={}){o.headers={...(o.headers||{}),...(tok?{authorization:tok}:{})};if(o.body&&!(o.body instanceof FormData)){o.headers['content-type']='application/json';o.body=JSON.stringify(o.body)}
 let r;try{r=await fetch(A+'/api'+u,o)}catch{toast('اتصال به سرور برقرار نشد');throw 0}const j=await r.json().catch(()=>({}));if(!r.ok){toast(j.error||'خطا');throw j}return j}
const toast=(t,k)=>{snd(k||(/نشد|خطا|اشتباه|معتبر نیست|لازم|برقرار|زیاد|ممکن نیست/.test(t)?'err':'ok'));const d=document.createElement('div');d.className='ts';d.textContent=t;document.body.append(d);setTimeout(()=>d.remove(),2800)};
const grad=id=>{const h=(id*67)%360;return`linear-gradient(135deg,hsl(${h},75%,70%),hsl(${(h+50)%360},70%,60%))`};
const art=p=>`<div class="art" style="background-image:${p.image?`url(${A+p.image})`:grad(p.id)}">${p.image?'':p.name[0]}<span class="hr" onclick="event.stopPropagation();fav(${p.id},this)">${wish.includes(p.id)?I.heartF:I.heart}</span></div>`;
window.fav=(id,el)=>{wish=wish.includes(id)?wish.filter(x=>x!=id):[...wish,id];S('wish',wish);el.innerHTML=wish.includes(id)?I.heartF:I.heart};
function modal(id,html,cls=''){let o=$('#'+id);if(!(o&&o.classList.contains('on')))snd('open');if(!o){o=document.createElement('div');o.id=id;document.body.append(o);o.onclick=e=>{if(e.target===o)o.classList.remove('on')}}o.className='ov on '+cls;o.innerHTML=`<div class="md glass"><button class="ib x" aria-label="بستن" onclick="this.closest('.ov').classList.remove('on')">${I.x}</button>${html}</div>`}
const close=()=>document.querySelectorAll('.ov').forEach(o=>o.classList.remove('on'));
function boot(){const LOGO=C.logo?A+C.logo:'assets/logo.png';if(C.c1)document.documentElement.style.setProperty('--v',C.c1);if(C.c2)document.documentElement.style.setProperty('--p',C.c2);
const pg=[['index.html','خانه'],['products.html','محصولات'],['about.html','درباره'],['contact.html','تماس']],cur=location.pathname.split('/').pop()||'index.html';
$('#hdr').innerHTML=`<nav class="glass"><a class="lg" href="index.html"><img src="${LOGO}" alt="لوگو"><span>${C.brand}<small>${C.role}</small></span></a>${pg.map(([h,t])=>`<a class="l ${h==cur?'on':''}" href="${h}">${t}</a>`).join('')}<button class="ib" id="mu" aria-label="صدا">${I.snd(!mute)}</button><button class="ib" id="us" aria-label="حساب">${I.user}</button><button class="ib" id="ct" aria-label="سبد">${I.cart}<span class="bd" id="cn">۰</span></button></nav>`;
$('#ftr').innerHTML=`<footer class="glass w"><p>© ${C.brand}</p><p>${[C.phone,C.insta&&'@'+C.insta,C.address].filter(Boolean).join(' — ')}</p></footer>`;if(C.announce)$('#hdr').insertAdjacentHTML('beforebegin',`<div class="an">${C.announce}</div>`);
$('#mu').onclick=()=>{mute=!mute;localStorage.mute=mute?1:0;$('#mu').innerHTML=I.snd(!mute);snd('click')};
const sync=()=>{S('cart',cart);$('#cn').textContent=cart.reduce((s,i)=>s+i.q,0).toLocaleString('fa-IR')};
const pp=id=>P.find(p=>p.id==id),sub=()=>cart.reduce((s,i)=>s+(pp(i.id)?.price||0)*i.q,0);
window.add=id=>{const i=cart.find(i=>i.id==id);i?i.q++:cart.push({id,q:1});sync();toast('به سبد اضافه شد','add')};
window.chg=(id,d)=>{const i=cart.find(i=>i.id==id);i.q+=d;if(i.q<1)cart=cart.filter(x=>x.id!=id);sync();openCart()};
function openCart(){cart=cart.filter(i=>pp(i.id));modal('cartM',`<h2>سبد خرید</h2>${cart.length?cart.map(i=>{const p=pp(i.id);return`<div class="ci">${art(p).replace(/<span.*?<\/span>/,'')}<span>${p.name}<br><b class="price">${T(p.price*i.q)}</b></span><button class="ib" onclick="chg(${p.id},-1)">−</button>${i.q.toLocaleString('fa-IR')}<button class="ib" onclick="chg(${p.id},1)">+</button></div>`}).join('')+`<h3 style="margin:14px 0">جمع: ${T(sub())}</h3><button class="btn v" onclick="checkout()">ادامه و پرداخت</button>`:'<p>سبد خالی است. از بخش محصولات شروع کنید.</p>'}`,'dr')}
$('#ct').onclick=async()=>{if(!P.length)await load();openCart()};
function authM(next){modal('authM',`<h2>ورود یا ثبت‌نام</h2><p style="color:var(--mut);font-size:14px">برای پرداخت باید وارد حساب شوید.</p><div class="tabs"><button class="chip on" id="tl">ورود</button><button class="chip" id="tr">ثبت‌نام</button></div><input id="au" placeholder="نام کاربری"><input id="aw" type="password" placeholder="رمز عبور (حداقل ۶ کاراکتر)"><button class="btn v" id="go">ورود</button>`);
 let reg=0;const set=r=>{reg=r;$('#go').textContent=r?'ساخت حساب':'ورود';$('#tl').classList.toggle('on',!r);$('#tr').classList.toggle('on',r)};$('#tl').onclick=()=>set(0);$('#tr').onclick=()=>set(1);
 $('#go').onclick=async()=>{const r=await api(reg?'/register':'/login',{method:'POST',body:{username:$('#au').value.trim(),password:$('#aw').value}});tok=r.token;me=r.user;localStorage.t=tok;S('u',me);acc();close();toast('خوش آمدید');if(me.role=='admin'&&!next){location.href='admin.html';return}next&&next()}}
const acc=()=>{$('#us').innerHTML=me?I.userok:I.user};acc();
$('#us').onclick=()=>me?modal('accM',`<h2>سلام ${me.username}</h2><br><button class="btn s" onclick="myOrders()">سفارش‌ها</button> ${me.role=='admin'?'<a class="btn v" href="admin.html">پنل مدیریت</a> ':''}<button class="btn" onclick="localStorage.clear();location.reload()">خروج</button>`):authM();

window.checkout=()=>{if(!me)return authM(checkout);if(!cart.length)return;
 modal('coM',`<h2>تکمیل سفارش</h2><h3 class="price">جمع: ${T(sub())}</h3><input id="cp" placeholder="کد تخفیف (اختیاری)"><button class="btn v" id="go2">ثبت سفارش و پرداخت</button>`);
 $('#go2').onclick=async()=>{const o=await api('/orders',{method:'POST',body:{items:cart,coupon:$('#cp').value.trim()}}).catch(()=>0);if(o){cart=[];sync();pay(o.id)}}};
window.pay=async id=>{const[o,s]=await Promise.all([api('/orders/'+id),api('/settings')]);const rej=o.status=='rejected';
 const body=o.status=='approved'?`<h2 class="ok">✓ پرداخت تأیید شد</h2><p>سفارش شما ثبت و آماده است.</p>${o.confirmFile?`<br><a class="btn v" target="_blank" href="${A+o.confirmFile}?t=${tok}">دانلود فایل سفارش</a>`:''}`:o.status=='review'?`<h2>فیش در حال بررسی است</h2><p>${o.ai?.reason||''}<br>نتیجه در «سفارش‌ها» نمایش داده می‌شود.</p>`:
 `<p>مبلغ قابل پرداخت</p><h1 class="price">${T(o.total)}</h1>${o.coupon?`<small>کد ${o.coupon} اعمال شد</small>`:''}<br><div class="cc"><img src="${LOGO}" alt="">${s.card}<small>${s.owner} — ${s.bank}</small></div><br><button class="btn s sm" onclick="navigator.clipboard.writeText('${s.card.replace(/-/g,'')}');toast('کپی شد')">کپی شماره کارت</button>
 <p style="margin:12px 0;font-size:14px">مبلغ را واریز کنید و عکس فیش را بارگذاری کنید. هوش مصنوعی فیش را بررسی می‌کند.</p>${rej?`<p class="no">رد شد: ${o.ai?.reason||''}</p>`:''}<input type="file" id="rc" accept="image/*"><button class="btn v" id="sb">ارسال فیش</button><div id="sc"></div>`;
 modal('payM',body);if(o.status=='approved'){snd('ok');confetti()}const sb=$('#sb');if(sb)sb.onclick=async()=>{const f=$('#rc').files[0];if(!f)return toast('عکس فیش را انتخاب کنید');$('#sc').innerHTML='<br><div class="scan"></div><p>در حال بررسی فیش…</p>';const fd=new FormData;fd.append('receipt',f);await api(`/orders/${id}/receipt`,{method:'POST',body:fd}).catch(()=>0);pay(id)}};
window.myOrders=async()=>{const os=await api('/orders');modal('ordM',`<h2>سفارش‌ها</h2>${os.map(o=>`<div class="ci"><span>#${String(o.id).slice(-6)}<br><b class="price">${T(o.total)}</b></span><span class="st ${o.status=='approved'?'ok':o.status=='rejected'?'no':''}">${stl[o.status]}</span><button class="btn s sm" onclick="pay(${o.id})">باز کردن</button></div>`).join('')||'<p>هنوز سفارشی ثبت نشده.</p>'}`)};
const card=p=>`<article class="glass card reveal">${art(p)}<div class="i"><small>${p.cat||''}</small><h3>${p.name}</h3><p style="font-size:13px;color:var(--mut)">${p.desc}</p><div class="row"><span class="price">${T(p.price)}</span><button class="btn v sm" onclick="add(${p.id})">افزودن</button></div></div></article>`;

const home=$('#home');if(home){home.innerHTML=`<section class="glass hero reveal"><div><small>سلام، من</small><h1>${C.brand}</h1><h2>${C.role}</h2><p>${C.heroText}</p><a class="btn" href="products.html">دیدن محصولات</a> <a class="btn s" href="contact.html">تماس با ما</a></div>
<div class="pf"><div class="fr"><img src="${LOGO}" alt="${C.brand}"></div><div class="fl glass s1"><b>${C.stats[0][0]}</b>${C.stats[0][1]}</div><div class="fl glass s2"><b>${C.stats[1][0]}</b>${C.stats[1][1]}</div></div></section>
<section class="glass blk"><span class="lab">درباره فروشگاه</span><h2>${C.aboutTitle}</h2><div class="stats">${C.stats.map(s=>`<div><b>${s[0]}</b>${s[1]}</div>`).join('')}</div></section>
<section class="glass blk"><span class="lab">مزایا</span><h2>چرا از ما خرید کنید</h2><div class="sv">${C.services.map((s,i)=>`<div><div class="ic" style="background:${s[2]}">${I.sv[i%4]}</div><b>${s[0]}</b><p>${s[1]}</p></div>`).join('')}</div></section>
<section class="glass blk"><span class="lab">امکانات</span><h2>خرید راحت‌تر با این امکانات</h2><div class="tl">${C.tools.map(t=>`<span>${t}</span>`).join('')}</div></section>
<section class="glass blk"><div class="row"><div><span class="lab">محصولات</span><h2>منتخب‌ها</h2></div><a class="btn s sm" href="products.html">همه محصولات</a></div><div class="grid" id="featured"></div></section>
<section class="glass blk"><span class="lab">مراحل کار</span><h2>مسیر سفارش</h2><div class="pr">${C.process.map((s,i)=>`<div><b>۰${(i+1).toLocaleString('fa-IR')}</b><br><strong>${s[0]}</strong><br><small>${s[1]}</small></div>`).join('')}</div></section>
<section class="glass blk"><span class="lab">نظرات</span><h2>مشتریان چه می‌گویند</h2><div class="rv">${C.reviews.map(r=>`<div>«${r[1]}»<br><small>${r[0]}</small></div>`).join('')}</div></section>
<section class="glass blk ct"><div><span class="lab">تماس</span><h2>سؤالی دارید؟</h2><p style="color:var(--mut)">پیام بگذارید تا پاسخ بدهیم.${C.phone?`<br>تلفن: ${C.phone}`:''}${C.insta?`<br>اینستاگرام: @${C.insta}`:''}${C.address?`<br>${C.address}`:''}</p></div><div style="position:relative;z-index:1">${cform()}</div><div class="orb"></div></section>`;
 load().then(()=>$('#featured').innerHTML=P.slice(0,4).map(card).join('')||'<p>به‌زودی…</p>')}
function cform(){return`<input id="cn1" placeholder="نام شما"><textarea id="cm" rows="4" placeholder="پیام شما"></textarea><button class="btn" onclick="sendMsg()">ارسال پیام</button>`}
window.sendMsg=async()=>{await api('/contact',{method:'POST',body:{name:$('#cn1').value,text:$('#cm').value}});toast('پیام ارسال شد');$('#cm').value=''};
const cf=$('#cf');if(cf)cf.innerHTML=cform();
const pl=$('#plist');if(pl)load().then(()=>{let cat='همه';$('#chips').innerHTML=['همه','علاقه‌مندی‌ها',...new Set(P.map(p=>p.cat))].map(c=>`<button class="chip ${c=='همه'?'on':''}">${c}</button>`).join('');
 const draw=()=>{const q=$('#q').value.trim(),s=$('#sort').value;let a=P.filter(p=>(cat=='همه'||(cat=='علاقه‌مندی‌ها'?wish.includes(p.id):p.cat==cat))&&(p.name+p.desc).includes(q));if(s=='lo')a.sort((x,y)=>x.price-y.price);if(s=='hi')a.sort((x,y)=>y.price-x.price);pl.innerHTML=a.map(card).join('')||'<p>محصولی پیدا نشد.</p>'};
 $('#chips').onclick=e=>{if(e.target.tagName!='BUTTON')return;cat=e.target.textContent;document.querySelectorAll('#chips .chip').forEach(c=>c.classList.toggle('on',c==e.target));draw()};$('#q').oninput=draw;$('#sort').onchange=draw;draw()});
sync();

const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in')),{threshold:.05});document.querySelectorAll('.blk').forEach(b=>io.observe(b));window.authM=authM;dispatchEvent(new Event('booted'))}
fetch(A+'/api/site').then(r=>r.json()).then(x=>Object.assign(C,x)).catch(()=>{}).finally(boot);
